name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: jhacr01.azurecr.io
  IMAGE_NAME: demo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
